# Generated by Django 4.1.2 on 2022-11-10 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('num', models.IntegerField(verbose_name='Numero')),
                ('depto', models.CharField(max_length=15)),
                ('localidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la enfermedad')),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='EquiposDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Inyecciones',
            },
        ),
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipo de mascota',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animales'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_dni',
            field=models.IntegerField(verbose_name='DNI'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de turno')),
                ('horario', models.TimeField()),
                ('equipo_diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.equiposdiagnostico')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.animal')),
            ],
        ),
        migrations.CreateModel(
            name='MascotaVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('fecha_vacuna', models.DateField(verbose_name='Fecha Vacuna')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.animal')),
            ],
            options={
                'verbose_name_plural': 'Mascotas Vacunas',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('se_curo', models.BooleanField(default=True, verbose_name='Está sano')),
                ('enfermedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.enfermedad')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.animal')),
            ],
            options={
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadInyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(verbose_name='Fecha de aplicacion')),
                ('enfermedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.enfermedad')),
                ('inyeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.inyeccion')),
            ],
            options={
                'verbose_name_plural': 'Enfermedades inyecciones',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.tipomascota'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinaria.direccion'),
        ),
    ]
