# Generated by Django 4.1.2 on 2022-11-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_direccion_enfermedad_equiposdiagnostico_inyeccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='depto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='num',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='se_curo',
            field=models.BooleanField(verbose_name='Está sano'),
        ),
    ]
