# Generated by Django 4.1.2 on 2022-11-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_direccion_piso_alter_direccion_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='se_curo',
            field=models.BooleanField(default=True, verbose_name='Está sano'),
        ),
    ]
