# Generated by Django 4.1.2 on 2022-11-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0004_alter_historial_se_curo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la mascota'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='localidad',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la enfermedad'),
        ),
        migrations.AlterField(
            model_name='enfermedad',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equiposdiagnostico',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inyeccion',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mascotavacuna',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipomascota',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
